# Generated by Django 4.0.3 on 2022-03-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0003_alter_niveau_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='applicable',
            field=models.CharField(choices=[('A', 'théorique'), ('B', 'intermédiaire'), ('C', 'pratique')], default='B', max_length=1),
        ),
    ]
