# Generated by Django 4.0.3 on 2022-03-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0008_alter_fiche_diffusion_alter_fiche_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='annee_film',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de production'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='annee_publication',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de publication'),
        ),
    ]
