# Generated by Django 4.0.3 on 2022-03-26 17:26

import ckeditor.fields
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0009_alter_fiche_annee_film_alter_fiche_annee_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.CharField(max_length=64, verbose_name='Entrée')),
                ('formes_alternatives', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, null=True, size=None, verbose_name='Formes alternatives (pluriels, abréviations, etc)')),
                ('definition', ckeditor.fields.RichTextField(blank=True, verbose_name='Définition')),
            ],
            options={
                'verbose_name': 'Entrée du glossaire',
                'verbose_name_plural': 'Entrées du glossaire',
            },
        ),
    ]
