# Generated by Django 4.0.3 on 2022-03-27 12:39

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0010_entreeglossaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeglossaire',
            name='entree',
            field=models.CharField(max_length=128, verbose_name='Entrée'),
        ),
        migrations.AlterField(
            model_name='entreeglossaire',
            name='formes_alternatives',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, null=True, size=None, verbose_name='Formes alternatives (pluriels, abréviations, etc)'),
        ),
    ]
