# Generated by Django 4.0.3 on 2022-03-30 20:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0012_entreecalendrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', ckeditor.fields.RichTextField(blank=True, verbose_name='Notes')),
                ('fiches_associees', models.ManyToManyField(blank=True, to='fichier.fiche', verbose_name='Fiches associées')),
                ('motscles', models.ManyToManyField(blank=True, to='fichier.motcle', verbose_name='Mots-clés associées')),
                ('themes', models.ManyToManyField(blank=True, to='fichier.theme', verbose_name='Thèmes associées')),
            ],
            options={
                'verbose_name': "Entrée de l'agenda",
                'verbose_name_plural': "Entrées de l'agenda",
            },
        ),
        migrations.DeleteModel(
            name='EntreeCalendrier',
        ),
    ]
