# Generated by Django 4.0.3 on 2022-04-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0013_entreeagenda_delete_entreecalendrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeagenda',
            name='motscles',
            field=models.ManyToManyField(blank=True, to='fichier.motcle', verbose_name='Mots-clés associés'),
        ),
        migrations.AlterField(
            model_name='entreeagenda',
            name='themes',
            field=models.ManyToManyField(blank=True, to='fichier.theme', verbose_name='Thèmes associés'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='categorie2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_categorie2', to='fichier.categorie', verbose_name='Deuxième catégorie'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='categorie3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_categorie3', to='fichier.categorie', verbose_name='Troisième catégorie'),
        ),
    ]
