# Generated by Django 4.0.3 on 2022-04-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0014_alter_entreeagenda_motscles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='applicable',
            field=models.CharField(choices=[('A', 'informatif'), ('B', 'intermédiaire'), ('C', 'pratique')], default='B', max_length=1),
        ),
    ]
