# Generated by Django 4.0.3 on 2022-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0015_alter_niveau_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorielibre',
            name='nom',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nom de la catégorie libre'),
        ),
        migrations.AlterField(
            model_name='entreeglossaire',
            name='entree',
            field=models.CharField(max_length=128, unique=True, verbose_name='Entrée'),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='nom',
            field=models.CharField(max_length=64, unique=True, verbose_name='Mot-clé'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='nom',
            field=models.CharField(max_length=64, unique=True, verbose_name='Thème'),
        ),
    ]
