# Generated by Django 4.0.3 on 2022-04-10 19:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0016_alter_categorielibre_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeagenda',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='en_savoir_plus',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='En savoir plus'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='focus',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Focus'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='lesplus',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Les plus'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='plan_du_site',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Plan du site'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='presentation',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Présentation'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='problematique',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Problématique'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='quatrieme_de_couverture',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Quatrième de couverture'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='reserves',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Dans ce texte, vous pouvez encadrer un terme par des crochets pour qu'ils devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]). Dans ce texte, les adresses internet (https://... ou http://...) sont automatiquement transformées en liens cliquables.", verbose_name='Réserves'),
        ),
    ]
