# Generated by Django 4.0.3 on 2022-04-12 07:14

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0018_alter_entreeagenda_fiches_associees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeagenda',
            name='fiches_associees',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="Les éléments de cette entrée sont ordonnés. Vous pouvez les ajouter dans l'ordre qui vous convient, mais aussi les trier par la suite", to='fichier.fiche', verbose_name='Fiches associées'),
        ),
        migrations.AlterField(
            model_name='entreeagenda',
            name='motscles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="Les éléments de cette entrée sont ordonnés. Vous pouvez les ajouter dans l'ordre qui vous convient, mais aussi les trier par la suite", to='fichier.motcle', verbose_name='Mots-clés associés'),
        ),
        migrations.AlterField(
            model_name='entreeagenda',
            name='themes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="Les éléments de cette entrée sont ordonnés. Vous pouvez les ajouter dans l'ordre qui vous convient, mais aussi les trier par la suite", to='fichier.theme', verbose_name='Thèmes associés'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='categories_libres',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="Les éléments de cette entrée sont ordonnés. Vous pouvez les ajouter dans l'ordre qui vous convient, mais aussi les trier par la suite", to='fichier.categorielibre', verbose_name='Catégories libres'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fiches_connexes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="Les éléments de cette entrée sont ordonnés. Vous pouvez les ajouter dans l'ordre qui vous convient, mais aussi les trier par la suite", to='fichier.fiche', verbose_name='Fiches connexes'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='mots_cles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="Les éléments de cette entrée sont ordonnés. Vous pouvez les ajouter dans l'ordre qui vous convient, mais aussi les trier par la suite", to='fichier.motcle', verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='themes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="Les éléments de cette entrée sont ordonnés. Vous pouvez les ajouter dans l'ordre qui vous convient, mais aussi les trier par la suite", to='fichier.theme', verbose_name='Thèmes'),
        ),
    ]
