# Generated by Django 4.0.3 on 2022-04-21 14:08

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0019_alter_entreeagenda_fiches_associees_and_more'),
    ]

    operations = [
        UnaccentExtension()
    ]
