# Generated by Django 4.0.3 on 2022-04-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0020_auto_20220421_1608'),
    ]

    operations = [
    ]
