# Generated by Django 4.0.3 on 2022-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0022_entreeagenda_marque_fiche_marque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='acteurs',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Acteur(s)'),
        ),
    ]
