# Generated by Django 4.0.3 on 2022-04-29 16:19

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0023_fiche_acteurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=512, verbose_name='Nom')),
                ('format_A4', models.BooleanField(default=False, verbose_name="Présentation sous forme d'une unique page A4")),
                ('contenu', ckeditor.fields.RichTextField(blank=True, verbose_name='Contenu')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
        ),
    ]
