# Generated by Django 4.0.3 on 2022-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0024_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='format_bibl',
            field=models.CharField(blank=True, help_text='Format attendu: ??.? x ??.? cm, ?? pages', max_length=1024, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='applicable',
            field=models.CharField(choices=[('A', 'informatif'), ('B', 'pratique'), ('C', 'opérationnel')], default='B', max_length=1),
        ),
    ]
