# Generated by Django 4.0.3 on 2022-10-08 08:35

import ckeditor.fields
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0026_alter_entreeglossaire_entree'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntetePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=32, unique=True)),
                ('texte', ckeditor.fields.RichTextField(blank=True, verbose_name="Texte de l'entête")),
            ],
        ),
        migrations.AlterField(
            model_name='entreeglossaire',
            name='formes_alternatives',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, null=True, size=None, verbose_name='Signification et formes alternatives'),
        ),
    ]
