# Generated by Django 4.0.3 on 2022-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0027_entetepage_alter_entreeglossaire_formes_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeagenda',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='entreeglossaire',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
