# Generated by Django 4.0.3 on 2022-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0028_entreeagenda_date_derniere_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeagenda',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
