# Generated by Django 4.0.3 on 2022-10-16 09:12

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0029_alter_entreeagenda_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeagenda',
            name='urls',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1024, verbose_name='Adresse'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='entreeglossaire',
            name='urls',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1024, verbose_name='Adresse'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='fiche',
            name='urls',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1024, verbose_name='Adresse'), blank=True, null=True, size=None),
        ),
    ]
