# Generated by Django 4.0.3 on 2022-10-24 14:19

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0030_entreeagenda_urls_entreeglossaire_urls_fiche_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeagenda',
            name='motscles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="L'ordre des éléments peut être changé glisser/déposer", to='fichier.motcle', verbose_name='Étiquettes associées'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='mots_cles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="L'ordre des éléments peut être changé glisser/déposer", to='fichier.motcle', verbose_name='Étiquettes'),
        ),
    ]
