# Generated by Django 4.0.3 on 2022-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0031_alter_entreeagenda_motscles_alter_fiche_mots_cles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motcle',
            options={'verbose_name': 'Étiquette', 'verbose_name_plural': 'Étiquettes'},
        ),
        migrations.AlterField(
            model_name='motcle',
            name='nom',
            field=models.CharField(max_length=64, unique=True, verbose_name='Étiquette'),
        ),
    ]
