# Generated by Django 4.0.3 on 2022-11-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0032_alter_motcle_options_alter_motcle_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='categories_libres',
        ),
        migrations.DeleteModel(
            name='CategorieLibre',
        ),
    ]
