# Generated by Django 4.0.3 on 2022-11-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0033_remove_fiche_categories_libres_delete_categorielibre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotCle',
            new_name='Etiquette',
        ),
        migrations.RenameField(
            model_name='entreeagenda',
            old_name='motscles',
            new_name='etiquettes',
        ),
        migrations.RenameField(
            model_name='fiche',
            old_name='mots_cles',
            new_name='etiquettes',
        ),
    ]
