# Generated by Django 4.0.3 on 2022-11-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0034_rename_motcle_etiquette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeagenda',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fichier.niveau', verbose_name='Niveau dominant du contenu'),
        ),
    ]
