# Generated by Django 4.0.3 on 2022-11-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0037_alter_entreeagenda_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeagenda',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='illustrations_agenda'),
        ),
    ]
