# Generated by Django 4.0.3 on 2022-11-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0038_alter_entreeagenda_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeagenda',
            name='illustration_alt',
            field=models.CharField(default='', max_length=512, verbose_name="Texte alternatif à l'illustration (audiodescription)"),
        ),
        migrations.AlterField(
            model_name='entreeagenda',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='illustrations_agenda', verbose_name='Illustration'),
        ),
    ]
