# Generated by Django 4.0.3 on 2022-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0041_alter_entreeagenda_illustration_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='entetepage',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
