# Generated by Django 4.0.3 on 2022-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0043_theme_date_derniere_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeagenda',
            name='date_demande_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Demande de mise à jour'),
        ),
        migrations.AddField(
            model_name='fiche',
            name='date_demande_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Demande de mise à jour'),
        ),
    ]
