# Generated by Django 4.0.3 on 2023-06-10 09:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0044_entreeagenda_date_demande_mise_a_jour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeagenda',
            name='texte_court',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Encadrer un terme par des crochets pour qu'il devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]).", verbose_name='Texte court (print)'),
        ),
        migrations.RenameField(
            model_name='entreeagenda',
            old_name='notes',
            new_name='texte_long',
        ),
    ]
