# Generated by Django 4.0.3 on 2023-06-10 12:53

import ckeditor.fields
from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0045_remove_entreeagenda_notes_entreeagenda_texte_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeagenda',
            name='etiquettes_recherche',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="L'ordre des éléments peut être changé glisser/déposer", related_name='etiquettes_recherche', to='fichier.etiquette', verbose_name='Étiquettes de recherche'),
        ),
        migrations.AlterField(
            model_name='entreeagenda',
            name='etiquettes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="L'ordre des éléments peut être changé glisser/déposer", related_name='etiquettes_affichees', to='fichier.etiquette', verbose_name='Étiquettes affichées'),
        ),
        migrations.AlterField(
            model_name='entreeagenda',
            name='texte_long',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Encadrer un terme par des crochets pour qu'il devienne un lien vers l'entrée de glossaire correspondante (exemple: [aidant]).", verbose_name='Texte long (web)'),
        ),
    ]
