# Generated by Django 4.0.3 on 2023-12-13 12:59

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0046_entreeagenda_etiquettes_recherche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeagenda',
            name='etiquettes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="L'ordre des éléments peut être changé glisser/déposer", related_name='entreeagenda', to='fichier.etiquette', verbose_name='Étiquettes affichées'),
        ),
        migrations.AlterField(
            model_name='entreeagenda',
            name='etiquettes_recherche',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text="L'ordre des éléments peut être changé glisser/déposer", related_name='entreeagenda_recherche', to='fichier.etiquette', verbose_name='Étiquettes de recherche'),
        ),
    ]
