version: '2.2'

services:
  web:
    build:
        context: ./web
        dockerfile: Dockerfile.prod
    command: gunicorn aidants365.wsgi:application --bind 0.0.0.0:8080
    expose:
      - 8080
    volumes:
      - static_volume:/home/app/web/static
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - cache
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
        - 1337:80
    depends_on:
        - web
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

volumes:
  postgres_data:
  static_volume:
