# Generated by Django 4.0.3 on 2022-03-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='nom',
            field=models.CharField(default='nom', max_length=64, verbose_name='Nom complet'),
        ),
    ]
